/**
 * CTAS-7 Complete PM2 Ecosystem Configuration
 * Command Center Dashboard for Development & Client Onboarding
 *
 * Service Tiers:
 * - Tier 0: Document Intelligence (ABE)
 * - Tier 1: Core Agent Infrastructure
 * - Tier 2: Linear Integration
 * - Tier 3: Intelligence Services
 * - Tier 4: Memory Mesh v2.0 RC1
 * - Tier 5: Custom GPT Endpoints
 * - Tier 6: Tool Orchestration
 */

module.exports = {
  apps: [
    // ========== TIER 0: DOCUMENT INTELLIGENCE (ABE) ==========
    // NOTE: abe-local was FAKE CODE generated by Claude Code (2025-11-08)
    // Real ABE architecture: Firefly microkernel + Drive sync (Rust/Node.js ONLY)
    {
      name: 'abe-firefly',
      script: '/Users/cp5337/Developer/ctas-7-shipyard-staging/firefly-microkernel/target/release/abe-firefly',
      args: ['--port', '18191'],
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '150M',
      env: {
        RUST_LOG: 'info',
        FIREFLY_MODE: 'abe-document',
        MEMORY_FABRIC_CONNECTION: 'localhost:19014',
        NEURAL_MUX_CDN: 'localhost:18100',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/abe-firefly-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/abe-firefly-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 18191,
    },
    {
      name: 'abe-drive-sync',
      script: '/Users/cp5337/Developer/agent_os-Claude/abe-drive-sync.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '250M',
      env: {
        NODE_ENV: 'production',
        DRIVE_SYNC_PORT: '18192',
        ABE_SERVICE_ACCOUNT: '/Users/cp5337/Developer/agent_os-Claude/abe-service-account.json',
        GOOGLE_DRIVE_FOLDER_ID: 'YOUR_FOLDER_ID',
        SYNC_INTERVAL_MINUTES: '30',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/abe-drive-sync-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/abe-drive-sync-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 18192,
    },

    // ========== TIER 1: CORE AGENT INFRASTRUCTURE ==========
    {
      name: 'repoagent-gateway',
      script: '/Users/cp5337/Developer/ctas-7-shipyard-staging/ctas7-repoagent/target/release/gateway',
      args: [],
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        RUST_LOG: 'info',
        CTAS_API_KEY: 'ctas7-gateway-2025-secure-key-natasha-zoe-orbital',
        GATEWAY_HTTP_PORT: '15180',
        GATEWAY_GRPC_PORT: '50055',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/repoagent-gateway-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/repoagent-gateway-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 15180,
    },
    {
      name: 'agent-mesh',
      script: '/Users/cp5337/Developer/ctas-7-shipyard-staging/ctas7-repoagent/target/release/ctas-agent-mesh',
      args: ['all'], // Start all agents
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        RUST_LOG: 'info',
        CLAUDE_META_AGENT_PORT: '50055',
        NATASHA_AGENT_PORT: '50052',
        GROK_AGENT_PORT: '50051',
        COVE_AGENT_PORT: '50053',
        ALTAIR_AGENT_PORT: '50054',
        GPT_AGENT_PORT: '50056',
        GEMINI_AGENT_PORT: '50057',
        ABE_AGENT_PORT: '50058',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/agent-mesh-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/agent-mesh-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 50055, // Claude Meta-Agent
    },

    // ========== TIER 2: LINEAR INTEGRATION ==========
    {
      name: 'linear-integration',
      script: '/Users/cp5337/Developer/ctas7-command-center/linear-integration-server.js',
      cwd: '/Users/cp5337/Developer/ctas7-command-center',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        LINEAR_API_KEY: process.env.LINEAR_API_KEY || 'YOUR_LINEAR_API_KEY',
        LINEAR_INTEGRATION_PORT: '15182',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/linear-integration-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/linear-integration-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 15182,
    },
    {
      name: 'linear-agent',
      script: '/Users/cp5337/Developer/ctas-7-shipyard-staging/ctas7-linear-agent-rust/target/release/ctas7-linear-agent',
      args: [],
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '250M',
      env: {
        RUST_LOG: 'info',
        LINEAR_AGENT_PORT: '18180',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/linear-agent-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/linear-agent-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 18180,
    },

    // ========== TIER 3: INTELLIGENCE SERVICES ==========
    {
      name: 'osint-engine',
      script: 'python',
      args: ['/Users/cp5337/Developer/ctas7-shipyard-system/enhanced-osint-engine.py', '--api', '--port', '18200'],
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        PYTHONUNBUFFERED: '1',
        OSINT_CONFIG_PATH: '/Users/cp5337/Developer/ctas7-shipyard-system/osint-config.json',
        VALID_KEYS_PATH: '/Users/cp5337/Developer/ctas7-shipyard-system/valid-keys.env',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/osint-engine-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/osint-engine-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 18200,
    },
    {
      name: 'corporate-analyzer',
      script: 'python',
      args: ['/Users/cp5337/Developer/ctas7-shipyard-system/ctas7-corporate-entity-analyzer.py', '--api', '--port', '18201'],
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        PYTHONUNBUFFERED: '1',
        OSINT_CONFIG_PATH: '/Users/cp5337/Developer/ctas7-shipyard-system/osint-config.json',
        VALID_KEYS_PATH: '/Users/cp5337/Developer/ctas7-shipyard-system/valid-keys.env',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/corporate-analyzer-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/corporate-analyzer-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 18201,
    },

    // ========== TIER 4: MEMORY MESH v2.0 RC1 ==========
    {
      name: 'sledis-cache',
      script: '/Users/cp5337/Developer/ctas-7-shipyard-staging/ctas7-sledis/target/release/sledis',
      args: ['--port', '19014', '--grpc-port', '20014'],
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '400M',
      env: {
        RUST_LOG: 'info',
        SLEDIS_MODE: 'production',
        MEMORY_MESH_VERSION: '2.0-RC1',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/sledis-cache-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/sledis-cache-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 19014,
    },
    {
      name: 'neural-mux',
      script: '/bin/bash',
      args: ['-c', '"/Users/cp5337/Developer/ctas-7-shipyard-staging/Cognitive Tactics Engine/cte-backend/cte-neural-mux/target/release/cte-neural-mux"'],
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '350M',
      env: {
        RUST_LOG: 'info',
        NEURAL_MUX_GRPC_PORT: '50051',
        NEURAL_MUX_WEB_BRIDGE_PORT: '15001',
        CONTEXT_MESH_PORT: '19011',
        ATOMIC_CLIPBOARD_PORT: '19012',
        THALMIC_FILTER_PORT: '19013',
        VOICE_GATEWAY_PORT: '19015',
        SHUTTLE_SYNC_PORT: '19016',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/neural-mux-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/neural-mux-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 50051,
    },

    // ========== TIER 5: CUSTOM GPT ENDPOINTS ==========
    {
      name: 'zoe-agent',
      script: 'node',
      args: ['/Users/cp5337/Developer/ctas-7-shipyard-staging/ctas7-orbital-ingest/zoe_agent_interface.js'],
      cwd: '/Users/cp5337/Developer/ctas-7-shipyard-staging/ctas7-orbital-ingest',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        ZOE_PORT: '58474',
        WOLFRAM_APP_ID: 'QUTVWY963T',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/zoe-agent-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/zoe-agent-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 58474,
    },
    // Note: Natasha is accessible via repoagent-gateway (15180) and agent-mesh (50052)

    // ========== TIER 6: TOOL ORCHESTRATION ==========
    {
      name: 'tool-server',
      script: '/Users/cp5337/Developer/ctas-7-shipyard-staging/tools/tool-server/server.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        PORT: '18295',
        NODE_ENV: 'production',
      },
      output: '/Users/cp5337/Developer/ctas7-command-center/logs/tool-server-out.log',
      error: '/Users/cp5337/Developer/ctas7-command-center/logs/tool-server-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      port: 18295,
    },
  ],
};
