# NYX-TRACE Government-Compliant Anaconda Environment
# CTAS 0.1 → CTAS 7.0 Integration Environment
# Classification: UNCLASSIFIED//FOR OFFICIAL USE ONLY
# Purpose: Intelligence analysis and geospatial operations

name: nyx-trace-ctas7
channels:
  - conda-forge
  - defaults
  - anaconda

dependencies:
  # Python Core (Government-approved version)
  - python=3.11

  # ============================================================================
  # INTELLIGENCE & AI CAPABILITIES
  # ============================================================================

  # AI/LLM Integration (Security-vetted packages)
  - openai>=1.0.0              # OpenAI API client
  # Note: anthropic not available in conda, use pip fallback

  # Natural Language Processing
  - spacy>=3.8.0               # Advanced NLP for intelligence extraction
  - nltk>=3.9.1                # Natural language toolkit
  - textblob>=0.18.0           # Sentiment analysis

  # ============================================================================
  # GEOSPATIAL INTELLIGENCE (GIS/GEOINT)
  # ============================================================================

  # Core Geospatial Stack
  - geopandas>=1.0.1           # Geospatial data structures
  - folium>=0.19.0             # Interactive mapping
  - h3-py>=4.0.0               # Uber H3 hexagonal hierarchical geospatial indexing
  - osmnx>=2.0.0               # OpenStreetMap network analysis
  - shapely>=2.0.0             # Geometric operations
  - pyproj>=3.7.0              # Cartographic projections
  - geopy>=2.4.0               # Geocoding and distance calculations
  - rtree>=1.3.0               # Spatial indexing

  # Advanced GIS Tools
  - rasterio>=1.4.0            # Raster data I/O
  - fiona>=1.10.0              # Vector data I/O
  - gdal>=3.9.0                # Geospatial Data Abstraction Library
  - cartopy>=0.23.0            # Cartographic projections for matplotlib

  # ============================================================================
  # DATA ANALYSIS & MACHINE LEARNING
  # ============================================================================

  # Core Analytics
  - pandas>=2.2.0              # Data manipulation and analysis
  - numpy>=2.0.0               # Numerical computing
  - scipy>=1.14.0              # Scientific computing
  - scikit-learn>=1.6.0        # Machine learning algorithms

  # Statistical Analysis
  - statsmodels>=0.14.0        # Statistical modeling
  - networkx>=3.4.0            # Network analysis and graph theory

  # ============================================================================
  # VISUALIZATION & DASHBOARD
  # ============================================================================

  # Interactive Visualization
  - plotly>=5.24.0             # Interactive plotting
  - matplotlib>=3.9.0          # Static plotting
  - seaborn>=0.13.0            # Statistical data visualization
  - pydeck>=0.9.0              # WebGL-powered visualization for geospatial data

  # Dashboard Framework
  - streamlit>=1.41.0          # Web application framework

  # ============================================================================
  # WEB SCRAPING & OSINT
  # ============================================================================

  # HTTP & Web Tools
  - requests>=2.32.0           # HTTP library
  - beautifulsoup4>=4.13.0     # HTML/XML parsing
  - lxml>=5.3.0                # XML and HTML processing
  - aiohttp>=3.10.0            # Async HTTP client/server

  # Content Extraction
  - readability-lxml>=0.8.0    # Article extraction
  # Note: trafilatura not available in conda, use pip fallback

  # ============================================================================
  # DATABASE & STORAGE
  # ============================================================================

  # SQL Databases
  - sqlalchemy>=2.0.0          # SQL toolkit and ORM
  - psycopg2>=2.9.0            # PostgreSQL adapter
  - geoalchemy2>=0.15.0        # Spatial extensions for SQLAlchemy

  # NoSQL Databases
  - pymongo>=4.12.0            # MongoDB driver

  # Cloud Storage
  - boto3>=1.38.0              # AWS SDK

  # ============================================================================
  # DATA FORMATS & SERIALIZATION
  # ============================================================================

  - openpyxl>=3.1.0            # Excel file handling
  - xlrd>=2.0.0                # Excel reading
  - pyyaml>=6.0.0              # YAML parsing
  - toml>=0.10.0               # TOML parsing
  - xmltodict>=0.14.0          # XML to dict conversion

  # ============================================================================
  # SECURITY & COMPLIANCE
  # ============================================================================

  - cryptography>=44.0.0       # Cryptographic recipes and primitives
  - pyjwt>=2.9.0               # JSON Web Token implementation
  - python-dotenv>=1.0.0       # Environment variable management

  # ============================================================================
  # DEVELOPMENT & TESTING
  # ============================================================================

  - pytest>=8.3.0              # Testing framework
  - pytest-asyncio>=0.24.0     # Async testing support
  - ipython>=8.29.0            # Enhanced interactive Python shell
  - jupyter>=1.1.0             # Jupyter notebook
  - jupyterlab>=4.3.0          # JupyterLab environment

  # Code Quality
  - black>=24.10.0             # Code formatting
  - flake8>=7.1.0              # Linting
  - mypy>=1.13.0               # Static type checking

  # ============================================================================
  # SYSTEM UTILITIES
  # ============================================================================

  - tqdm>=4.67.0               # Progress bars
  - python-dateutil>=2.9.0     # Date/time utilities
  - pytz>=2024.2               # Timezone definitions
  - click>=8.1.0               # Command-line interface creation

  # ============================================================================
  # PIP-ONLY PACKAGES (Not available in conda channels)
  # ============================================================================

  - pip>=24.0
  - pip:
    # AI/LLM (conda unavailable)
    - anthropic>=0.50.0
    - google-generativeai>=0.8.5

    # OSINT Tools (conda unavailable)
    - shodan>=1.31.0
    - trafilatura>=2.0.0
    - feedparser>=6.0.11

    # Specialized Geospatial (conda unavailable)
    - whitebox>=2.3.6
    - fastkml>=1.1.0
    - pykml>=0.2.0

    # TAXII/STIX Threat Intelligence (conda unavailable)
    - cabby>=0.1.23
    - taxii2-client>=2.3.0

    # Cloud/Database (conda unavailable)
    - supabase>=2.15.0
    - mapbox>=0.18.1

    # Web Automation (conda unavailable)
    - playwright>=1.52.0

    # Utilities (conda unavailable)
    - cytoolz>=1.0.1
    - wolframalpha>=5.1.3

# ============================================================================
# ENVIRONMENT VARIABLES REQUIRED
# ============================================================================
# Create .env file with:
# - OPENAI_API_KEY
# - ANTHROPIC_API_KEY
# - SHODAN_API_KEY
# - SUPABASE_URL
# - SUPABASE_KEY
# - MAPBOX_TOKEN
# - DATABASE_URL (PostgreSQL with PostGIS)

# ============================================================================
# POST-INSTALLATION STEPS
# ============================================================================
# 1. conda env create -f environment.yml
# 2. conda activate nyx-trace-ctas7
# 3. python -m spacy download en_core_web_sm
# 4. playwright install
# 5. Verify GDAL installation: gdalinfo --version
